// generated by config.pl
// modify the top of that file, not this one

#ifndef _CONFIG_H

#define TABLEBITS (13)
#define CPUCYCLES (7)
#define CLOCKRATE (200000000)
#define PRUNUM (1)
#define TABLELEN  (8192) 
#define TABLEPREC (19)
#define TABLEMULT (524288)

#endif
